include = ["**/Cargo.toml", "taplo.toml"]

[formatting]
allowed_blank_lines = 1
array_auto_collapse = true
array_auto_expand = true
compact_arrays = true
indent_string = "    "
trailing_newline = true

[[rule]]
formatting = { reorder_arrays = true, reorder_keys = true }
include = ["Cargo.toml"]
keys = ["package", "dependencies"]
